name = "Silicon Valley Adventure PLUS"
author = "André Augusto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94f1df1d64448849cabe41f1035b4775a3ae70d9163936f056e3b2259bf726a9"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.2"]
